In [1]:
import numpy as np

In [3]:
#1. Create a null vector of size 10 but the fifth value which is 1.
x = np.zeros(10)
print(x)
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#2. Create a vector with values ranging from 10 to 49.
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
output = np.nonzero(x)
print("Indices of non zero elements are",output)

Indices of non zero elements are (array([0, 1, 4], dtype=int64),)


In [9]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.35660169 0.82464871 0.78049833 0.84411368 0.77971186 0.9596006
  0.19060322 0.80246619 0.86845317 0.85598158]
 [0.87732937 0.86793154 0.31375879 0.68715487 0.69028675 0.79726339
  0.40293218 0.14877555 0.04153239 0.50015014]
 [0.67906162 0.25281924 0.23796567 0.12053136 0.4818331  0.85142555
  0.43552755 0.14351708 0.28418907 0.80195414]
 [0.19018871 0.54040681 0.68205577 0.47941199 0.59606056 0.38135241
  0.75095223 0.26854448 0.00668443 0.17787698]
 [0.46116362 0.2748919  0.0108379  0.01974252 0.20101817 0.92980336
  0.0137425  0.51134913 0.8362475  0.67808178]
 [0.38136226 0.01807814 0.66264996 0.48214783 0.91209724 0.15656711
  0.05077256 0.2833158  0.82252567 0.59694215]
 [0.22040853 0.34720563 0.26815605 0.2039019  0.62366774 0.63256536
  0.62017417 0.38191825 0.3892343  0.6437377 ]
 [0.95624686 0.27510605 0.90003485 0.07229524 0.99132918 0.04421893
  0.03919981 0.28966033 0.98950283 0.26755459]
 [0.82672661 0.86575422 0.36207772 0.74571441 0.02199628 0.114713

In [10]:
#6. Create a random vector of size 30 and find the mean value.
x = np.random.random(30)
print(x)
output = np.mean(x)
print("mean of x",output)

[0.39131918 0.2721896  0.21980365 0.49370118 0.95999039 0.79284492
 0.23179571 0.5033644  0.00557528 0.40512199 0.52080949 0.92946239
 0.6035237  0.045441   0.6987576  0.99895399 0.30793496 0.55183676
 0.8904158  0.23326251 0.13101146 0.92362045 0.60815039 0.6823561
 0.52466239 0.95420921 0.53361005 0.73351384 0.90673847 0.24990885]
mean of x 0.5434628567892462
